version: 0.0
os: linux
files:
  - source: target/helios-1.0.war
    destination: /home/ec2-user/

permissions:
  - object: /home/ec2-user/helios-1.0.war
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 60
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: ec2-user