name: Deploy to AWS EC2 via CodeDeploy

on:
  push:
    branches:
      - proxy-dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Build WAR
        run: mvn clean package -DskipTests

      - name: Zip Artifacts
        run: zip -r deploy.zip appspec.yml scripts/ target/helios-1.0.war

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Upload to S3
        run: aws s3 cp deploy.zip s3://helios-bck/

      - name: Deploy via CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name Helios \
            --deployment-group-name HeliosGroup \
            --s3-location bucket=helios-bck,bundleType=zip,key=deploy.zip
